### PR TITLE
fix: Fix crash when creating new directory

### LINKED ISSUE #6: Fails creating a new directory
The script fails when trying to create a new directory on first export from new issue.
If the directory is present there is no problem.

### PR DESCRIPTION
**Pull request by adambrgmn**
This commit also solves a problem with exporting issues with a special name.

fix #6

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -263,6 +263,8 @@ function main() {
       const anchor = getMarkdownAnchor(err.message);
       openUrl(`${pkg.homepage}/blob/master/docs/errors.md${anchor}`);
     }
+  } finally {
+    exit(); // eslint-disable-line
```
Comment (adambrgmn) [inline src/index.js]: Just to pint out that this PR will also declaratively exit the program after it's done.
Just a formality actually, and for clarity, but doesn't affect anything really.
